DROP TABLE TODO;
DROP SEQUENCE TODO_SQ;
CREATE TABLE TODO(
  ID NUMBER(4) PRIMARY KEY,
  CONTENTS VARCHAR2(256) NOT NULL,
  IS_DONE  NUMBER(1) DEFAULT 0
);
CREATE SEQUENCE TODO_SQ NOCACHE NOCYCLE MAXVALUE 9999;

-- CREATE
INSERT INTO TODO (ID, CONTENTS) VALUES (1, 'flask', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (2, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (3, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (4, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (5, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (6, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (7, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (8, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (9, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (10, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (11, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (12, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (13, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (14, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (15, '포트폴리오작성', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (16, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS) VALUES (17, '포트폴리오작성', 0);

-- READ
SELECT * FROM TODO ORDER BY ID;
SELECT * FROM TODO WHERE ID = 1;

-- UPDATE
UPDATE TODO SET CONTENTS='바꿀내용', IS_DONE=1 WHERE ID=1;

-- DELETE
-- DELETE FROM TODO WHERE ID=2;

-- next_id
SELECT NVL(MAX(ID), 0)+1 FROM TODO;

COMMIT;